version: '3.8'

services:
  chesswar:    
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chesswar
    ports: 
      - "${API_PORT:-8080}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
    volumes:
      - chesswar_data:/app/data
      - chesswar_logs:/app/logs
    restart: unless-stopped

    

  chesswar-client:    
    build:
      context: ../chesswar-client-test-api
      dockerfile: Dockerfile
    container_name: chesswar-client
    ports:
      - "${CLIENT_PORT:-4200}:4200" # клиент доступен с хоста
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - chesswar
    restart: unless-stopped

  config-maker:
    build:
      context: ../config-maker
      dockerfile: Dockerfile
    container_name: config-maker
    ports:
      - "${CONFIG_MAKER_PORT:-4199}:4199" # config maker доступен с хоста
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - chesswar
    restart: unless-stopped

volumes:
  chesswar_data:
    name: chesswar_data
  chesswar_logs:
    name: chesswar_logs
      